### ISSUE TITLE
Pouch-db does not return info when trying to get credentials for a new user

### ISSUE THREAD

**Issue by ram-verida** [verida/verida-js#150] opened 2022-02-17 02:38 UTC
https://github.com/verida/verida-js/blob/bc29ebd6b887b505677e5d411a6e9b40c85ac7d9/packages/client-ts/src/context/engines/verida/database/db-encrypted.ts#L92

Current Behaviour:

- Create a new account on vault
- Go to data > credentials
- Notice that the app shows white screen and does nothing

Finding is that, db Initialisation for credential is going to a time out state where the above line on client-ts does not return back any information and is stuck in the await request.

**Comment by ram-verida** [comment] 2022-02-17 02:39
@tahpot please refer to this above issue. I will try resolving this.

**Comment by tahpot** [comment] 2022-02-17 02:53
@ram-verida is this on both Android and iOS?

I've seen similar unusual behaviour in Android.

**Comment by ram-verida** [comment] 2022-02-17 03:50
@tahpot this finding has been made on Android only so far, yet to verify for iOS, will update.

**Comment by tahpot** [comment] 2022-02-17 03:54
@ram-verida This issue also exists on Android:  https://github.com/verida/vault-mobile/issues/202

I think Android has an underlying issue with CouchDB and I suspect this is the root cause of the Android issues.

We may need a call with @pkhien95 to help onboard you with more background information.

If this is an Android issue, this issue should probably be in the vault repo.

**Comment by tahpot** [comment] 2022-04-25 00:29
@ram-verida Should we close this issue assuming it's associated with the Android issues?

**Comment by nick-verida** [comment] 2022-05-02 03:08
I'm closing this

**Closed by nick-verida** 2022-05-02 03:08 UTC
Labels: bug

**Comment by ram-verida** [comment] 2022-05-03 03:00
Sorry for the delayed response, its ok that this is closed but an important thread for archives until we have truly resolved android bugs.
